
---
flags:
  WeakRef: useWeakRefs
  FinalizationRegistry: useWeakRefs
  class-fields-private: usePrivateClassFields
  class-methods-private: usePrivateMethods
  class-fields-private-in: usePrivateIn
  class-static-fields-public: usePublicStaticClassFields
  class-static-fields-private: usePrivateStaticClassFields
  class-static-methods-private: usePrivateMethods
  error-cause: useErrorCause
  Intl.DateTimeFormat-dayPeriod: useIntlDateTimeFormatDayPeriod
  SharedArrayBuffer: useSharedArrayBuffer
  Atomics: useSharedArrayBuffer
  Array.prototype.at: useAtMethod
  TypedArray.prototype.at: useAtMethod
  String.prototype.at: useAtMethod
  top-level-await: useTopLevelAwait
  array-find-from-last: useArrayFindLastMethod
skip:
  features:
    - Atomics.waitAsync
    # https://bugs.webkit.org/show_bug.cgi?id=174931
    - regexp-lookbehind
    - cleanupSome
    - Intl.Locale-info
    - resizable-arraybuffer
    - Object.hasOwn
    - Temporal
    - import-assertions
    - json-modules
    - class-static-block
    - Intl.DisplayNames-v2
    - Intl.DateTimeFormat-extend-timezonename
    - callable-boundary-realms
  paths:
  files:
    # https://github.com/claudepache/es-legacy-function-reflection
    - test/built-ins/ThrowTypeError/unique-per-realm-function-proto.js
    - test/built-ins/Function/prototype/restricted-property-arguments.js
    - test/built-ins/Function/prototype/restricted-property-caller.js

    # Slightly different formatting. We should update test262 side.
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/en-US.js
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/fractionalSecondDigits.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-de-DE.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-en-US.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-zh-TW.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-de-DE.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-en-US.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-rounding.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-zh-TW.js
    - test/intl402/NumberFormat/prototype/format/unit-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/unit-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-zh-TW.js

    # New ICU (66~) raises a different failure
    - test/intl402/Locale/constructor-apply-options-canonicalizes-twice.js
    - test/intl402/Locale/constructor-non-iana-canon.js
    - test/intl402/Locale/likely-subtags.js

    # Pass only in ICU 68~
    - test/intl402/Locale/constructor-options-region-valid.js
    - test/intl402/Locale/constructor-tag.js
    - test/intl402/Intl/getCanonicalLocales/complex-language-subtag-replacement.js
    - test/intl402/Intl/getCanonicalLocales/complex-region-subtag-replacement.js
    - test/intl402/Intl/getCanonicalLocales/grandfathered.js
    - test/intl402/Intl/getCanonicalLocales/canonicalized-tags.js
    - test/intl402/Intl/getCanonicalLocales/unicode-ext-key-with-digit.js
    - test/intl402/supportedLocalesOf-unicode-extensions-ignored.js

    # ICU canonicalization bug
    # https://unicode-org.atlassian.net/browse/ICU-21367
    - test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-yes-to-true.js

    # Failing because we are building WebKit with very old ICU headers
    - test/intl402/DateTimeFormat/prototype/formatRange/date-same-returns-single-date.js
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/argument-date-string.js
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/argument-near-time-boundaries.js
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/argument-to-integer.js
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/argument-tonumber-throws.js
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/builtin.js
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/date-is-infinity-throws.js
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/date-is-nan-throws.js
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/date-same-returns-single-date.js
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/date-x-greater-than-y-throws.js
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/length.js
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/name.js
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/pattern-on-calendar.js
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts/prop-desc.js
    - test/intl402/ListFormat/constructor/constructor/locales-invalid.js
    - test/intl402/ListFormat/constructor/constructor/locales-valid.js
    - test/intl402/ListFormat/constructor/constructor/newtarget-undefined.js
    - test/intl402/ListFormat/constructor/constructor/options-invalid.js
    - test/intl402/ListFormat/constructor/constructor/options-localeMatcher-invalid.js
    - test/intl402/ListFormat/constructor/constructor/options-order.js
    - test/intl402/ListFormat/constructor/constructor/options-style-invalid.js
    - test/intl402/ListFormat/constructor/constructor/options-style-valid.js
    - test/intl402/ListFormat/constructor/constructor/options-throwing-getters.js
    - test/intl402/ListFormat/constructor/constructor/options-toobject-prototype.js
    - test/intl402/ListFormat/constructor/constructor/options-toobject.js
    - test/intl402/ListFormat/constructor/constructor/options-type-invalid.js
    - test/intl402/ListFormat/constructor/constructor/options-type-valid.js
    - test/intl402/ListFormat/constructor/constructor/options-undefined.js
    - test/intl402/ListFormat/constructor/constructor/proto-from-ctor-realm.js
    - test/intl402/ListFormat/constructor/constructor/subclassing.js
    - test/intl402/ListFormat/constructor/length.js
    - test/intl402/ListFormat/constructor/name.js
    - test/intl402/ListFormat/constructor/prop-desc.js
    - test/intl402/ListFormat/constructor/prototype.js
    - test/intl402/ListFormat/constructor/supportedLocalesOf/basic.js
    - test/intl402/ListFormat/constructor/supportedLocalesOf/branding.js
    - test/intl402/ListFormat/constructor/supportedLocalesOf/length.js
    - test/intl402/ListFormat/constructor/supportedLocalesOf/locales-invalid.js
    - test/intl402/ListFormat/constructor/supportedLocalesOf/name.js
    - test/intl402/ListFormat/constructor/supportedLocalesOf/options-localeMatcher-invalid.js
    - test/intl402/ListFormat/constructor/supportedLocalesOf/options-null.js
    - test/intl402/ListFormat/constructor/supportedLocalesOf/options-toobject.js
    - test/intl402/ListFormat/constructor/supportedLocalesOf/options-undefined.js
    - test/intl402/ListFormat/constructor/supportedLocalesOf/prop-desc.js
    - test/intl402/ListFormat/constructor/supportedLocalesOf/result-type.js
    - test/intl402/ListFormat/instance/extensibility.js
    - test/intl402/ListFormat/instance/prototype.js
    - test/intl402/ListFormat/prototype/constructor/prop-desc.js
    - test/intl402/ListFormat/prototype/format/branding.js
    - test/intl402/ListFormat/prototype/format/en-us-default.js
    - test/intl402/ListFormat/prototype/format/en-us-disjunction.js
    - test/intl402/ListFormat/prototype/format/en-us-narrow.js
    - test/intl402/ListFormat/prototype/format/en-us-short.js
    - test/intl402/ListFormat/prototype/format/en-us-unit.js
    - test/intl402/ListFormat/prototype/format/es-es-long.js
    - test/intl402/ListFormat/prototype/format/es-es-narrow.js
    - test/intl402/ListFormat/prototype/format/es-es-short.js
    - test/intl402/ListFormat/prototype/format/iterable-getiterator-throw.js
    - test/intl402/ListFormat/prototype/format/iterable-invalid.js
    - test/intl402/ListFormat/prototype/format/iterable-iteratorclose.js
    - test/intl402/ListFormat/prototype/format/iterable-iteratorstep-throw.js
    - test/intl402/ListFormat/prototype/format/iterable-iteratorvalue-throw.js
    - test/intl402/ListFormat/prototype/format/iterable-undefined.js
    - test/intl402/ListFormat/prototype/format/iterable.js
    - test/intl402/ListFormat/prototype/format/length.js
    - test/intl402/ListFormat/prototype/format/name.js
    - test/intl402/ListFormat/prototype/format/prop-desc.js
    - test/intl402/ListFormat/prototype/formatToParts/branding.js
    - test/intl402/ListFormat/prototype/formatToParts/en-us-default.js
    - test/intl402/ListFormat/prototype/formatToParts/en-us-disjunction.js
    - test/intl402/ListFormat/prototype/formatToParts/en-us-narrow.js
    - test/intl402/ListFormat/prototype/formatToParts/en-us-short.js
    - test/intl402/ListFormat/prototype/formatToParts/en-us-unit.js
    - test/intl402/ListFormat/prototype/formatToParts/es-es-long.js
    - test/intl402/ListFormat/prototype/formatToParts/es-es-narrow.js
    - test/intl402/ListFormat/prototype/formatToParts/es-es-short.js
    - test/intl402/ListFormat/prototype/formatToParts/iterable-getiterator-throw.js
    - test/intl402/ListFormat/prototype/formatToParts/iterable-invalid.js
    - test/intl402/ListFormat/prototype/formatToParts/iterable-iteratorclose.js
    - test/intl402/ListFormat/prototype/formatToParts/iterable-iteratorstep-throw.js
    - test/intl402/ListFormat/prototype/formatToParts/iterable-iteratorvalue-throw.js
    - test/intl402/ListFormat/prototype/formatToParts/iterable-undefined.js
    - test/intl402/ListFormat/prototype/formatToParts/iterable.js
    - test/intl402/ListFormat/prototype/formatToParts/length.js
    - test/intl402/ListFormat/prototype/formatToParts/name.js
    - test/intl402/ListFormat/prototype/formatToParts/prop-desc.js
    - test/intl402/ListFormat/prototype/prop-desc.js
    - test/intl402/ListFormat/prototype/resolvedOptions/branding.js
    - test/intl402/ListFormat/prototype/resolvedOptions/caching.js
    - test/intl402/ListFormat/prototype/resolvedOptions/length.js
    - test/intl402/ListFormat/prototype/resolvedOptions/name.js
    - test/intl402/ListFormat/prototype/resolvedOptions/order.js
    - test/intl402/ListFormat/prototype/resolvedOptions/prop-desc.js
    - test/intl402/ListFormat/prototype/resolvedOptions/type.js
    - test/intl402/ListFormat/prototype/toStringTag/toString.js
    - test/intl402/ListFormat/prototype/toStringTag/toStringTag.js
    - test/intl402/NumberFormat/constructor-compactDisplay-compact.js
    - test/intl402/NumberFormat/constructor-compactDisplay-no-compact.js
    - test/intl402/NumberFormat/constructor-notation.js
    - test/intl402/NumberFormat/constructor-signDisplay.js
    - test/intl402/NumberFormat/constructor-unit.js
    - test/intl402/NumberFormat/constructor-unitDisplay.js
    - test/intl402/NumberFormat/currencyDisplay-unit.js
    - test/intl402/NumberFormat/prototype/format/engineering-scientific-de-DE.js
    - test/intl402/NumberFormat/prototype/format/engineering-scientific-en-US.js
    - test/intl402/NumberFormat/prototype/format/engineering-scientific-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/engineering-scientific-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/engineering-scientific-zh-TW.js
    - test/intl402/NumberFormat/prototype/format/notation-compact-de-DE.js
    - test/intl402/NumberFormat/prototype/format/notation-compact-en-US.js
    - test/intl402/NumberFormat/prototype/format/notation-compact-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/notation-compact-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/notation-compact-zh-TW.js
    - test/intl402/NumberFormat/prototype/format/unit-de-DE.js
    - test/intl402/NumberFormat/prototype/format/unit-en-US.js
    - test/intl402/NumberFormat/prototype/format/unit-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/units.js
    - test/intl402/NumberFormat/prototype/formatToParts/engineering-scientific-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/engineering-scientific-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/engineering-scientific-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/engineering-scientific-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/engineering-scientific-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/notation-compact-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/notation-compact-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/notation-compact-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/notation-compact-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/notation-compact-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/percent-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit.js
    - test/intl402/NumberFormat/prototype/resolvedOptions/compactDisplay.js
    - test/intl402/NumberFormat/style-unit.js
