
---
flags:
  BigInt: useBigInt
  WeakRef: useWeakRefs
  FinalizationRegistry: useWeakRefs
  class-fields-public: usePublicClassFields
  class-fields-private: usePrivateClassFields
skip:
  features:
    - SharedArrayBuffer
    - Atomics
    - Atomics.waitAsync
    # https://bugs.webkit.org/show_bug.cgi?id=174931
    - regexp-lookbehind

    - class-methods-private
    - class-static-fields-public
    - class-static-fields-private
    - class-static-methods-private
    - cleanupSome
    - host-gc-required
    # https://bugs.webkit.org/show_bug.cgi?id=202475
    - regexp-match-indices
    - top-level-await
    - Intl.DateTimeFormat-dayPeriod
    - Intl.ListFormat
  paths:
    - test/built-ins/DataView/prototype/getBigInt64
    - test/built-ins/DataView/prototype/getBigUint64
    - test/built-ins/DataView/prototype/setBigInt64

    # https://bugs.webkit.org/show_bug.cgi?id=190800
    - test/built-ins/TypedArray/prototype/Symbol.toStringTag/BigInt
    - test/built-ins/TypedArray/prototype/buffer/BigInt
    - test/built-ins/TypedArray/prototype/byteLength/BigInt
    - test/built-ins/TypedArray/prototype/byteOffset/BigInt
    - test/built-ins/TypedArray/prototype/copyWithin/BigInt
    - test/built-ins/TypedArray/prototype/entries/BigInt
    - test/built-ins/TypedArray/prototype/every/BigInt
    - test/built-ins/TypedArray/prototype/fill/BigInt
    - test/built-ins/TypedArray/prototype/filter/BigInt
    - test/built-ins/TypedArray/prototype/find/BigInt
    - test/built-ins/TypedArray/prototype/findIndex/BigInt
    - test/built-ins/TypedArray/prototype/forEach/BigInt
    - test/built-ins/TypedArray/prototype/includes/BigInt
    - test/built-ins/TypedArray/prototype/indexOf/BigInt
    - test/built-ins/TypedArray/prototype/join/BigInt
    - test/built-ins/TypedArray/prototype/keys/BigInt
    - test/built-ins/TypedArray/prototype/lastIndexOf/BigInt
    - test/built-ins/TypedArray/prototype/length/BigInt
    - test/built-ins/TypedArray/prototype/map/BigInt
    - test/built-ins/TypedArray/prototype/reduce/BigInt
    - test/built-ins/TypedArray/prototype/reduceRight/BigInt
    - test/built-ins/TypedArray/prototype/reverse/BigInt
    - test/built-ins/TypedArray/prototype/set/BigInt
    - test/built-ins/TypedArray/prototype/slice/BigInt
    - test/built-ins/TypedArray/prototype/some/BigInt
    - test/built-ins/TypedArray/prototype/sort/BigInt
    - test/built-ins/TypedArray/prototype/subarray/BigInt
    - test/built-ins/TypedArray/prototype/toLocaleString/BigInt
    - test/built-ins/TypedArray/prototype/toString/BigInt
    - test/built-ins/TypedArray/prototype/values/BigInt
    - test/built-ins/TypedArrayConstructors/BigInt64Array
    - test/built-ins/TypedArrayConstructors/BigUint64Array
    - test/built-ins/TypedArrayConstructors/ctors-bigint
    - test/built-ins/TypedArrayConstructors/from/BigInt
    - test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/BigInt
    - test/built-ins/TypedArrayConstructors/internals/Get/BigInt
    - test/built-ins/TypedArrayConstructors/internals/GetOwnProperty/BigInt
    - test/built-ins/TypedArrayConstructors/internals/HasProperty/BigInt
    - test/built-ins/TypedArrayConstructors/internals/OwnPropertyKeys/BigInt
    - test/built-ins/TypedArrayConstructors/internals/Set/BigInt
    - test/built-ins/TypedArrayConstructors/of/BigInt

    # requires ICU APIs implementation
    # https://bugs.webkit.org/show_bug.cgi?id=213822
    - test/intl402/DateTimeFormat/prototype/formatRangeToParts
  files:
    # https://bugs.webkit.org/show_bug.cgi?id=186749
    - test/built-ins/RegExp/property-escapes/character-class.js

    # [[OwnPropertyKeys]] order with large integer index keys up to 2 ** 53 - 1
    # https://bugs.webkit.org/show_bug.cgi?id=186691
    - test/built-ins/Reflect/ownKeys/return-on-corresponding-order-large-index.js


    # https://bugs.webkit.org/show_bug.cgi?id=190800
    - test/built-ins/TypedArray/prototype/set/src-typedarray-big-throws.js
    - test/built-ins/TypedArrayConstructors/ctors/typedarray-arg/src-typedarray-big-throws.js
    - test/built-ins/TypedArrayConstructors/prototype/Symbol.toStringTag/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/bigint-Symbol.iterator.js
    - test/built-ins/TypedArrayConstructors/prototype/buffer/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/byteLength/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/byteOffset/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/copyWithin/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/entries/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/every/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/fill/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/filter/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/find/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/findIndex/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/forEach/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/indexOf/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/join/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/keys/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/lastIndexOf/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/length/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/map/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/reduce/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/reduceRight/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/reverse/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/set/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/slice/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/some/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/sort/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/subarray/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/toLocaleString/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/toString/bigint-inherited.js
    - test/built-ins/TypedArrayConstructors/prototype/values/bigint-inherited.js

    # requires ICU 65 (https://unicode-org.atlassian.net/browse/ICU-20654)
    - test/intl402/RelativeTimeFormat/prototype/format/en-us-numeric-auto.js
    - test/intl402/RelativeTimeFormat/prototype/formatToParts/en-us-numeric-auto.js

    # Do not work with ICU 64, and work with ICU 66 or later.
    - test/intl402/NumberFormat/prototype/format/numbering-systems.js

    # Catalina bot is using older SDK which is shipping < 64 ICU.
    - test/intl402/NumberFormat/constructor-compactDisplay-compact.js
    - test/intl402/NumberFormat/constructor-compactDisplay-no-compact.js
    - test/intl402/NumberFormat/constructor-notation.js
    - test/intl402/NumberFormat/constructor-signDisplay.js
    - test/intl402/NumberFormat/constructor-unit.js
    - test/intl402/NumberFormat/constructor-unitDisplay.js
    - test/intl402/NumberFormat/currencyDisplay-unit.js
    - test/intl402/NumberFormat/prototype/format/engineering-scientific-de-DE.js
    - test/intl402/NumberFormat/prototype/format/engineering-scientific-en-US.js
    - test/intl402/NumberFormat/prototype/format/engineering-scientific-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/engineering-scientific-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/engineering-scientific-zh-TW.js
    - test/intl402/NumberFormat/prototype/format/notation-compact-de-DE.js
    - test/intl402/NumberFormat/prototype/format/notation-compact-en-US.js
    - test/intl402/NumberFormat/prototype/format/notation-compact-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/notation-compact-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/notation-compact-zh-TW.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-de-DE.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-en-US.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-currency-zh-TW.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-de-DE.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-en-US.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-rounding.js
    - test/intl402/NumberFormat/prototype/format/signDisplay-zh-TW.js
    - test/intl402/NumberFormat/prototype/format/unit-de-DE.js
    - test/intl402/NumberFormat/prototype/format/unit-en-US.js
    - test/intl402/NumberFormat/prototype/format/unit-ja-JP.js
    - test/intl402/NumberFormat/prototype/format/unit-ko-KR.js
    - test/intl402/NumberFormat/prototype/format/unit-zh-TW.js
    - test/intl402/NumberFormat/prototype/format/units.js
    - test/intl402/NumberFormat/prototype/formatToParts/engineering-scientific-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/engineering-scientific-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/engineering-scientific-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/engineering-scientific-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/engineering-scientific-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/notation-compact-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/notation-compact-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/notation-compact-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/notation-compact-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/notation-compact-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/percent-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-currency-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/signDisplay-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-de-DE.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-en-US.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-ja-JP.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-ko-KR.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit-zh-TW.js
    - test/intl402/NumberFormat/prototype/formatToParts/unit.js
    - test/intl402/NumberFormat/prototype/resolvedOptions/compactDisplay.js
    - test/intl402/NumberFormat/style-unit.js
